include:
  - '/gitlab-ci/main.yml'

stages:
  # stage 和 stage 之间按照顺序串行执行
  # 相同stage的job并行执行
  - go-check-stage

# 环境变量
variables:
  _GO_INSTALL_DIR: "$CI_PROJECT_DIR"

  # git flags
  GIT_COMPARE_MODE: "all"

  # go flags
  GO_FLAGS: ""
  GO_TEST_FLAGS: '-gcflags="all=-l"'
  GO_EXCLUDE_OPTIONS: ""

  # go buile variables
  GO_BUILD_TARGET_DIR: "$CI_PROJECT_DIR/cmd"

  # go coverage variables
  GO_COVERAGE_DIFF_TARGET: "master"
  # GO_COVERAGE_DIFF_SOURCE: "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  # GO_COVERAGE_FILE: "$CI_PROJECT_DIR/log/coverage.out"
  # GO_COVERAGE_RATE: 0.65
  # GO_COVERAGE_EXCLUDES: ""

  # go cognitive variables
  GO_COGNITIVE_DIFF_TARGET: "master"
  # GO_COGNITIVE_DIFF_SOURCE: "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  # GO_COGNITIVE_OVER: 15
  # GO_COGNITIVE_EXCLUDES: ""

# disable cache
cache: {}
