#! /usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

git submodule init && git submodule update

PROJECT_ROOT="$(git rev-parse --show-toplevel)"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

if [[ "$GO_COGNITIVE_OVER" == "" ]]; then
    GO_COGNITIVE_OVER=15
fi

function _echo_and_run() {
    echo "$@"
    "$@"
    return $?
}

function _go_install() {
    local cmd="$1"
    type "$cmd" \
        || _echo_and_run go install github.com/distroy/git-go-tool/cmd/$cmd@latest \
        || _echo_and_run go install github.com/distroy/git-go-tool/cmd/$cmd
    return $?
}

_go_install git-diff-go-cognitive
_go_install git-diff-go-format

git-diff-go-cognitive \
    -branch "$against" || exit $?

git-diff-go-format \
    -branch "$against" || exit $?
