name: go

on:
  push:
    branches:
      # - "**"
      - master
      - release**
  pull_request:
    branches:
      - master
      - release**

env:
  GO111MODULE: on
  TZ: Asia/Shanghai
  PROJECT_URL: "${{ github.repositoryUrl }}"
  WORKSPACE: "${{ github.workspace }}"

jobs:
  go-build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        # name: go-setup
        with:
          go-version: "1.17.13"
      - run: make build-test

  go-format-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.13"
      - run: make setup
      - run: |
          git-diff-go-format

  go-cognitive-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.13"
      - run: make cognitive

  go-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.13"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: go mod download
      - run: make setup
      - run: make go-test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: go-coverage
          path: log/go-coverage.html
      - run: |
          git-diff-go-coverage -file log/go-coverage.out
