name: go

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  echo-env-job:
    runs-on: ubuntu-latest
  steps:
    - run: |
      echo "$GITHUB_BASE_REF"
      echo "$GITHUB_HEAD_REF"


  go-cognitive-job:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        # name: go-setup
        with:
          go-version: "1.12.17"
      - run: make cognitive

  go-test-job:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: go mod download
      - run: make go-test
