name: go

on:
  push:
    branches:
      # - "**"
      - master
      - release**
  pull_request:
    branches:
      - master
      - release**

env:
  GO111MODULE: on
  TZ: Asia/Shanghai
  PROJECT_URL: "${{ github.repositoryUrl }}"
  WORKSPACE: "${{ github.workspace }}"

jobs:
  go-build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        # name: go-setup
        with:
          go-version: "1.12.17"
      - run: make build-test

  go-format-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: make setup
      - run: |
          git-diff-go-format

  go-cognitive-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: make cognitive

  go-test-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: go mod download
      - run: make go-test

  go-test-coverage-job:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git checkout "$GITHUB_BASE_REF"
          git checkout "$GITHUB_HEAD_REF"
      - run: go mod download
      - run: make setup
      - run: make go-test-coverage
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: go-coverage
          path: log/go-coverage.html
      # - run: git-diff-go-coverage -mode all -rate 0.65 -file log/go-coverage.out
      - run: |
          # merge_base=$(git merge-base "$GITHUB_BASE_REF" "$GITHUB_HEAD_REF")
          # echo "merge base: $merge_base"
          # git-diff-go-coverage -branch $merge_base -rate 0.35 -file log/go-coverage.out
          git-diff-go-coverage -file log/go-coverage.out
